const actionTypes = {
  SET_PAGE: "SET_PAGE",
  SET_DESTINATION: "SET_DESTINATION",
  SET_DATES: "SET_DATES",
  SET_OPTIONS: "SET_OPTIONS",
  SET_PRICE: "SET_PRICE",
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
};

export default actionTypes;
